import './globals.css'

export const metadata = {
  title: 'Butas 18',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='max-w-5xl m-auto'>{children}</body>
    </html>
  )
}
